spring.application.name=backend

server.port=8080

spring.data.mongodb.uri=mongodb+srv://palagirisivanihithreddy:Palagirisiva123@intership.macoiwl.mongodb.net/?appName=Intership

spring.data.mongodb.database=college_management