spring.application.name=backend

server.port=8080

# ==========================
# MongoDB
# ==========================

spring.data.mongodb.uri=mongodb+srv://palagirisivanihithreddy:Palagirisiva123@intership.macoiwl.mongodb.net/?appName=Intership

spring.data.mongodb.database=college_management

# ==========================
# Ollama
# ==========================

spring.ai.ollama.base-url=http://localhost:11434

spring.ai.ollama.chat.options.model=qwen3

spring.ai.ollama.chat.options.temperature=0.3

# ==========================
# MCP Server
# ==========================

spring.ai.mcp.server.enabled=true

spring.ai.mcp.server.name=College MCP Server

spring.ai.mcp.server.version=1.0.0